### ISSUE TITLE
Сообщения об ошибках и др. "всплывающие окна"

### ISSUE THREAD

**Issue by taimyr** [nextgis/nextgismobile#22]
1) при загрузке некорректного (или битого) тайлового архива выводится сообщение, не проясняющее причин сбоя, ну то что нет причин - еще ладно, но оно (сообщение) висит несколько секунд и исчезает...
2) Если при загрузке большого тайлового архива ненамеренно "тапнуть" карту, этот "прогресс-бар" исчезает, что неудобно.
Предлагаю эти и им подобные окна держать в фоне и сделать "явное" закрытие.

**Comment by simgislab** [comment]
https://github.com/nextgis/android_gisapp/issues/106
