### ISSUE TITLE
Выборочное закрытие полей для редактирования

### ISSUE THREAD

**Issue by ghost** [nextgis/nextgismobile#24]
Нет возможности закрыть некоторые поля мобильной формы для редактирования.

**Comment by BishopGIS** [comment]
Вообще-то, возможность есть.
Если сделать кастомную форму при помощи http://nextgis.ru/nextgis-formbuilder/ и не добавлять контролы к некоторым полям, то их нельзя будет отредактировать.

**Comment by ghost** [comment]
Спасибо. Пропустил при чтении документации.
