### ISSUE TITLE
Возможность закрыть редактирование геометрии

### ISSUE THREAD

**Issue by ghost** [nextgis/nextgismobile#27]
Опциональное закрытие редактирования узлов, добавления или удаления объектов в отдельном слое.

**Comment by BishopGIS** [comment]
Кейс не понятен. Пользователь выбирает какой слой редактировать. Зачем нужны еще какие-то инструменты закрытия/открытия редактирования слоя.

**Comment by ghost** [comment]
Имелась в виду финализация геометрии, так то: отключить изменение формы полигона, удалении или добавление точки и т.п. Работа в финализированном слое предлагается только с атрибутами, без возможности изменения геометрии.
В мобильном приложении случается ошибочно перетянуть узел полигона при изменении его атрибутов. Это действие может быть замечено не сразу, что приводит к необходимости подтягивать инишиал формы для исправления геометрии.

**Comment by BishopGIS** [comment]
Открыл тикет nextgis/android_gisapp#406
